Qx1 : 0.0
Qx2 : 0.0
Qx3 : 3500000
Qx4 : 0.0
Qx5 : 0.0

Rx1 : 8000.0
Rx2 : 0.0

Zl0x : 500.0
Zu0x : 500.0
zl0x : 0.0
zu0x : 0.0

Zl1x : 500.0
Zu1x : 500.0
zl1x : 0.0
zu1x : 0.0

ZlNx : 0.0
ZuNx : 0.0
zlNx : 0
zuNx : 0

lmom : 0

Qy1 : 0.0
Qy2 : 10.0
Qy3 : 6500000
Qy4 : 0.0
Qy5 : 0.0

Ry1 : 10000.0
Ry2 : 5.0

Zl0y : 0.0
Zu0y : 0.0
zl0y : 0.0
zu0y : 0.0

Zl1y : 0.0
Zu1y : 0.0
zl1y : 0.0
zu1y : 0.0

ZlNy : 0.0
ZuNy : 0.0
zlNy : 0
zuNy : 0

kc_r : 80
tc_r : 10

kc_p : 50
tc_p : 10

arp_dl : 30
ark_dl : 0.02
app_dl : 20
apk_dl : 0.04

arp_sl : 40
ark_sl : 0.05
app_sl : 30
apk_sl : 0.04

arp_dr : 30
ark_dr : 0.05
app_dr : 20
apk_dr : 0.04

arp_sr : 40
ark_sr : 0.05
app_sr : 30
apk_sr : 0.04

com_gain : 0.5

pelv_xp : -0.4
pelv_yp : -0.8
zmp_xp : 0.0
zmp_yp : 0.0

K_fx : 0.0001
T_fx : 3.0

K_fy : 0.0001 
T_fy : 3.0

K_fz : 0.0001
T_fz : 3.0

mobgain1 : 40
mobgain2 : 40
mobgain3 : 40
mobgain4 : 60
mobgain5 : 40
mobgain6 : 40

ft : 0
dist : 1