Qx1 : 0.01
Qx2 : 0.01
Qx3 : 3500000
Qx4 : 0.01
Qx5 : 0.01

Rx1 : 8000.0
Rx2 : 5.0

Zl0x : 50.0
Zu0x : 50.0
zl0x : 0.0
zu0x : 0.0

Zl1x : 50.0
Zu1x : 50.0
zl1x : 0.0
zu1x : 0.0

ZlNx : 0.0
ZuNx : 0.0
zlNx : 0
zuNx : 0

lmom : 0

Qy1 : 0.001
Qy2 : 0.001
Qy3 : 3500000
Qy4 : 0.01
Qy5 : 0.01

Ry1 : 8000.0
Ry2 : 10.0

Zl0y : 50.0
Zu0y : 50.0
zl0y : 0.0
zu0y : 0.0

Zl1y : 50.0
Zu1y : 50.0
zl1y : 0.0
zu1y : 0.0

ZlNy : 0.0
ZuNy : 0.0
zlNy : 0
zuNy : 0

kc_r : 80
tc_r : 10

kc_p : 50
tc_p : 10

arp_dl : 30
ark_dl : 0.04
app_dl : 20
apk_dl : 0.05

arp_sl : 40
ark_sl : 0.04
app_sl : 30
apk_sl : 0.05

arp_dr : 30
ark_dr : 0.04
app_dr : 20
apk_dr : 0.05

arp_sr : 40
ark_sr : 0.04
app_sr : 30
apk_sr : 0.05

com_gain : 0.5

pelv_xp : -0.5
pelv_yp : -0.8
zmp_xp : 0.0
zmp_yp : 0.0

K_fx : 0.0001
T_fx : 3.0

K_fy : 0.0001 
T_fy : 3.0

K_fz : 0.0001
T_fz : 3.0

dobrgain1 : -2
dobrgain2 : -2
dobrgain3 : -2
dobrgain4 : -2
dobrgain5 : -2
dobrgain6 : -2

ft : 0
dist : 0

sim_mode : false
dob_gain : 2.5