Kl_roll_dsp : 40.0
Kl_pitch_dsp : 40.0
Kr_roll_dsp : 40.0
Kr_pitch_dsp : 40.0

Kl_roll_ssp : 45.0
Kl_pitch_ssp : 40.0
Kr_roll_ssp : 45.0
Kr_pitch_ssp : 40.0

Kpl_roll : -0.06 #0.05
Kpl_pitch : 0.06 #5
Kpr_roll : -0.06 #0.05
Kpr_pitch : 0.06

del_zmpx_gain : 2.6
del_zmpy_gain : 2.6

del_zmpx_gain_init : 2.2
del_zmpy_gain_init : 2.2

F_F_input_Kp : 0.0005 #0.0003
F_F_input_Kv : 4.0 #4.0

pelvR_kp : 0.0 #1.0
pelvR_kv : 0.0 #0.01
pelvP_kp : 0.0 #1.0
pelvP_kv : 0.0 #0.01

legxP : 0.003
legyP : 0.003
legzP : 0.003

com_kx : 0.0002
com_ky : 0.003
com_kz : 0.000

com_kx_init : 0.000
com_ky_init : 0.000
com_kz_init : 0.001

foot_swr : 0.0
foot_swp : 0.0

momPelvR_init : 0.001
momPelvP_init : 0.001
momPelvR : 0.05 #0.08
momPelvP : 0.05

swingR_init : 0.003
swingP_init : 0.003
swingR : 0.3
swingP : 0.3

controlwalk_time : 260 #352 #260

impact_theta : 180
impact_force : 200.0

dis_mpc_init : 153 #174, 153
dis_mpc_final : 180