Kl_roll_dsp : 30.0
Kl_pitch_dsp : 30.0
Kr_roll_dsp : 30.0
Kr_pitch_dsp : 30.0

Kl_roll_ssp : 30.0
Kl_pitch_ssp : 30.0
Kr_roll_ssp : 30.0
Kr_pitch_ssp : 30.0

Kpl_roll : -0.12
Kpl_pitch : 0.12
Kpr_roll : -0.12
Kpr_pitch : 0.12

del_zmpx_gain : 0.8
del_zmpy_gain : 0.8

F_F_input_Kp : 0.0004
F_F_input_Kv : 3.0

pelvR_kp : 1.0
pelvR_kv : 0.00
pelvP_kp : 1.0
pelvP_kv : 0.00