Qx1 : 500.0
Qx2 : 0.0
Qx3 : 500.0
Qx4 : 0.0
Qx5 : 0.0

Rx1 : 1.0
Rx2 : 0.0

Zl0x : 0.0
Zu0x : 0.0
zl0x : 0.0
zu0x : 0.0

Zl1x : 0.0
Zu1x : 0.0
zl1x : 0.0
zu1x : 0.0

ZlNx : 0.0
ZuNx : 0.0
zlNx : 0
zuNx : 0

lmom : 0

Qy1 : 1.0
Qy2 : 0.0
Qy3 : 30000.0
Qy4 : 0.0
Qy5 : 0.0

Ry1 : 2.0
Ry2 : 0.0

Zl0y : 0.0
Zu0y : 0.0
zl0y : 0.0
zu0y : 0.0

Zl1y : 0.0
Zu1y : 0.0
zl1y : 0.0
zu1y : 0.0

ZlNy : 0.0
ZuNy : 0.0
zlNy : 0
zuNy : 0

kc_r1 : 8
tc_r1 : 10

kc_r : 5
tc_r : 0.5

kc_p : 5
tc_p : 0.5

arp_dl : 5
ark_dl : 0.04
app_dl : 5
apk_dl : 0.04

arp_sl : 5
ark_sl : 0.03
app_sl : 5
apk_sl : 0.04

arp_dr : 5
ark_dr : 0.04
app_dr : 5
apk_dr : 0.04

arp_sr : 5
ark_sr : 0.03
app_sr : 5
apk_sr : 0.04

com_gain : 0.5

pelv_xp : -0.6
pelv_yp : -0.8
zmp_xp : 0.0
zmp_yp : 0.0

K_fx : 0.0001
T_fx : 3.0

K_fy : 0.0001 
T_fy : 3.0

K_fz : 0.0001
T_fz : 3.0

mobgain1 : 40
mobgain2 : 40
mobgain3 : 40
mobgain4 : 60
mobgain5 : 40
mobgain6 : 40

ft : 0
dist : 0
