Kl_roll_dsp : 30.0
Kl_pitch_dsp : 30.0
Kr_roll_dsp : 30.0
Kr_pitch_dsp : 30.0

Kl_roll_ssp : 35.0
Kl_pitch_ssp : 30.0
Kr_roll_ssp : 35.0
Kr_pitch_ssp : 30.0

Kpl_roll : -0.055
Kpl_pitch : 0.05
Kpr_roll : -0.055
Kpr_pitch : 0.05

del_zmpx_gain : 2.2
del_zmpy_gain : 2.2

del_zmpx_gain_init : 2.2
del_zmpy_gain_init : 2.2

F_F_input_Kp : 0.0005 #0.0003
F_F_input_Kv : 4.0 #4.0

pelvR_kp : 0.0 #1.0
pelvR_kv : 0.0 #0.01
pelvP_kp : 0.0 #1.0
pelvP_kv : 0.0 #0.01

legxP : 0.003
legyP : 0.003
legzP : 0.003

com_kx : 0.0003
com_ky : 0.0003
com_kz : 0.001

com_kx_init : 0.003
com_ky_init : 0.001
com_kz_init : 0.001

foot_swr : 0.0
foot_swp : 0.0

momPelvR_init : 0.01
momPelvP_init : 0.01
momPelvR : 0.05
momPelvP : 0.05

swingR_init : 0.03
swingP_init : 0.03
swingR : 0.05
swingP : 0.05


impact_theta : 0.0
impact_force : 550.0

dis_mpc_init : 1000 #174, 153
dis_mpc_final : 180


controlwalk_time : 260
