Kl_roll_dsp : 40.0
Kl_pitch_dsp : 40.0
Kr_roll_dsp : 40.0
Kr_pitch_dsp : 40.0

Kl_roll_ssp : 45.0
Kl_pitch_ssp : 40.0
Kr_roll_ssp : 45.0
Kr_pitch_ssp : 40.0

Kpl_roll : -0.045 #55
Kpl_pitch : 0.055 #5
Kpr_roll : -0.045
Kpr_pitch : 0.055

del_zmpx_gain : 2.6
del_zmpy_gain : 2.6

del_zmpx_gain_init : 2.2
del_zmpy_gain_init : 2.2

F_F_input_Kp : 0.0005 #0.0003
F_F_input_Kv : 4.0 #4.0

pelvR_kp : 0.0 #1.0
pelvR_kv : 0.0 #0.01
pelvP_kp : 0.0 #1.0
pelvP_kv : 0.0 #0.01

legxP : 0.003
legyP : 0.003
legzP : 0.003

com_kx : 0.0002
com_ky : 0.0004
com_kz : 0.0000

com_kx_init : 0.000
com_ky_init : 0.000
com_kz_init : 0.001

foot_swr : 0.0
foot_swp : 0.0

momPelvR_init : 0.001
momPelvP_init : 0.001
momPelvR : 0.006 #0.08
momPelvP : 0.006

swingR_init : 0.003
swingP_init : 0.003
swingR : 0.003
swingP : 0.003

controlwalk_time : 260 #260
